### ISSUE TITLE
Incompatible con plugin DMSF

### ISSUE THREAD

**Issue by aivorra** [danielanguita/Redmine-Inventory-Manager#19]
He montado un redmine con el plugin DMSF (para gestionar documentación) y ahora instalé RIM para probar la gestión de inventario, pero cuando lo instalo me deja de funcionar el DMSF. Al desinstalar RIM vuelve a funcionar el DMSF. ¿Qué logs te puedo pasar para ver en donde está la incompatibilidad en la instalación del plugin?

**Comment by w0www** [comment]
Buenas, 

tendrías que pasarnos el log de development o production del propio rails. Me suena que yo tuve el mismo problema. 

saludos

**Comment by aivorra** [comment]
A continuación les paso el log "production.log". En este log está el acceso al RIM sin problemas y luego intento acceder a "/projects/ceo-movil/dmsf" y el plugin DMSF me genera el error 404.

Cualquier otro dato que necesiten para analizarlo me avisan.

Connecting to database specified by database.yml
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Started GET "/" for 10.0.0.167 at 2015-08-31 12:38:28 -0300
Processing by WelcomeController#index as HTML
  Current user: aivorra (id=1)
  Rendered news/_news.html.erb (31.9ms)
  Rendered welcome/index.html.erb within layouts/base (89.5ms)
Completed 200 OK in 525.8ms (Views: 285.8ms | ActiveRecord: 9.8ms)
Started GET "/inventory" for 10.0.0.167 at 2015-08-31 12:38:31 -0300
Processing by InventoryController#index as HTML
  Current user: aivorra (id=1)
  Rendered plugins/redmine_inventory_manager/app/views/inventory/_top_menu.html.erb (4.1ms)
  Rendered plugins/redmine_inventory_manager/app/views/inventory/index.html.erb within layouts/base (11.9ms)
Completed 200 OK in 49.3ms (Views: 35.7ms | ActiveRecord: 1.7ms)
Started GET "/projects" for 10.0.0.167 at 2015-08-31 12:38:33 -0300
Processing by ProjectsController#index as HTML
  Current user: aivorra (id=1)
  Rendered projects/index.html.erb within layouts/base (19.5ms)
Completed 200 OK in 50.5ms (Views: 43.7ms | ActiveRecord: 0.7ms)
Started GET "/projects/ceo-movil" for 10.0.0.167 at 2015-08-31 12:38:42 -0300
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"ceo-movil"}
  Current user: aivorra (id=1)
  Rendered projects/_members_box.html.erb (3.9ms)
  Rendered news/_news.html.erb (7.3ms)
  Rendered projects/show.html.erb within layouts/base (24.7ms)
Completed 200 OK in 207.3ms (Views: 67.6ms | ActiveRecord: 10.7ms)
Started GET "/projects/ceo-movil/dmsf" for 10.0.0.167 at 2015-08-31 12:38:43 -0300

AbstractController::ActionNotFound (The action 'ceo-movil' could not be found for ProjectsController):
  actionpack (3.2.19) lib/abstract_controller/base.rb:116:in `process'
  actionpack (3.2.19) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.19) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.19) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `_run__3652283039958263341__call__3483360127946671983__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in `call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.55) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.55) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.55) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.55) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

**Comment by w0www** [comment]
El problema esta en el routes.rb. Ambos plugins se "pisan" y las rutas para RIM dejan de funcionar. La solución pasa por cambiar esas rutas para que sean mas especificas y funcionen con todas las rutas que necesita el plugin. Ahora mismo no encuentro el fix que ya tenia aplicado en una de mis ramas locales y no tengo tiempo para volver a programarlo pero puedes hacerlo tu.

La idea es cambiar las lineas 
get ':controller(/:action(/:id))'
post ':controller(/:action(/:id))'
put ':controller(/:action(/:id))'

por algo mas especifico.

**Comment by aivorra** [comment]
Sinceramente no manejo todavía la programación de Redmine y sus plugins por lo que seguiré aprendiendo un poco para ver como cambiar las 3 líneas. Gracias.
