### ISSUE TITLE
Error in dp migration on postgres

### ISSUE THREAD

**Issue by hojjatnikan** [danielanguita/Redmine-Inventory-Manager#6]
Hi
i want to run your project on redmine 2.6.1 on postgres database, i test it but there was some error in migration .
Please guide me 

Best Regards 
Hojjat Nikan

**Comment by danielanguita** [comment]
Hi,

I'm sorry, i haven't tested yet on postgres. Can you send me the log with the errors?

Daniel

**Comment by albertasva** [comment]
Hi

I tried to install plugin on Redmine 2.6.3 with postgress database and stepped on this same issue.
After some tweaking of migration scripts  005_foreign_keys_and_views.rb and 007_keys_and_modifications.rb I was able to install plugin.

However, when I tried to use it I encountered yet another SQL issue and gave up.
Unistallation of plugin using rake redmine:plugins:migrate RAILS_ENV=production VERSION=0 NAME=redmine_inventory_manager
also failed. After simple change of same migration scripts I completed uninstall.

**Details**

**Error log fragment during installation**

> ==  ForeignKeysAndViews: migrating ============================================
> -- execute("          ALTER TABLE `inventory_movements` ADD\n            CONSTRAINT `fk_inventory_movement_part` FOREIGN KEY (`inventory_part_id`)\n              REFERENCES `inventory_parts`(`id`)\n              ON DELETE NO ACTION\n              ON UPDATE NO ACTION;\n")
> rake aborted!
> StandardError: An error has occurred, this and all later migrations canceled:
> 
> PG::SyntaxError: ERROR:  syntax error at or near "`"
> LINE 1:           ALTER TABLE `inventory_movements` ADD
>                               ^
> :           ALTER TABLE `inventory_movements` ADD
>             CONSTRAINT `fk_inventory_movement_part` FOREIGN KEY (`inventory_part_id`)
>               REFERENCES `inventory_parts`(`id`)
>               ON DELETE NO ACTION
>               ON UPDATE NO ACTION;
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `async_exec'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `block in execute'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
> /var/lib/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:466:in `block in method_missing'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:438:in `block in say_with_time'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:438:in `say_with_time'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:458:in `method_missing'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:334:in `method_missing'
> /usr/share/redmine/plugins/redmine_inventory_manager/db/migrate/005_foreign_keys_and_views.rb:9:in `up'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:370:in `up'
> 

**Error log during execution**
> ...
> Started GET "/redmine/inventory" for 192.168.2.33 at 2015-05-12 16:16:48 +0300
> Processing by InventoryController#index as HTML
>   Current user: albertas (id=5)
> Completed 500 Internal Server Error in 10.9ms
> 
> ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error at or near "."
> LINE 9:     (SELECT `inventory_parts`.`part_number` AS `part_number`...
>                                      ^
> : SELECT in_movements.part_number as part_number,
>         in_movements.serial_number as serial_number, in_movements.category as category,
>         in_movements.part_description as description, in_movements.value,
>         IFNULL(in_movements.quantity,0) as input,
>         IFNULL(out_movements.quantity,0) as output,
>         (IFNULL(in_movements.quantity,0)-IFNULL(out_movements.quantity,0)) as stock,
>         GREATEST(IFNULL(in_movements.last_date,0), IFNULL(out_movements.last_date,0)) as last_movement
> ...  


**Error log fragment during uninstall**

> rake redmine:plugins:migrate RAILS_ENV=production VERSION=0 NAME=redmine_inventory_manager
> (in /usr/share/redmine)
> [DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
> Migrating redmine_inventory_manager (Redmine Inventory Manager Plugin)...
> ==  KeysAndModifications: reverting ===========================================
> -- uk_inventory_part_part_number()
> rake aborted!
> StandardError: An error has occurred, this and all later migrations canceled:
> 
> undefined method `uk_inventory_part_part_number' for #<KeysAndModifications:0xd9cf6b4>/var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:465:in `block in method_missing'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:438:in `block in say_with_time'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:438:in `say_with_time'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:458:in `method_missing'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:334:in `method_missing'
> /usr/share/redmine/plugins/redmine_inventory_manager/db/migrate/007_keys_and_modifications.rb:69:in `down'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:376:in `down'
> /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
> 

*Modified 005_foreign_keys_and_views.rb*

> class ForeignKeysAndViews < ActiveRecord::Migration
>     def self.up
>         execute <<-SQL
>           ALTER TABLE inventory_movements ADD
>             CONSTRAINT fk_inventory_movement_part FOREIGN KEY (inventory_part_id)
>               REFERENCES inventory_parts(id)
>               ON DELETE NO ACTION
>               ON UPDATE NO ACTION;
>         SQL
> 
>       execute <<-SQL
>           ALTER TABLE inventory_movements ADD
>             CONSTRAINT fk_inventory_movement_providor FOREIGN KEY (inventory_providor_id)
>               REFERENCES inventory_providors(id)
>               ON DELETE NO ACTION
>               ON UPDATE NO ACTION;
>         SQL
> 
>       execute <<-SQL
>         ALTER TABLE inventory_parts ADD
>           CONSTRAINT fk_inventory_parts_category FOREIGN KEY (inventory_category_id)
>             REFERENCES inventory_categories(id)
>             ON DELETE NO ACTION
>             ON UPDATE NO ACTION;
>       SQL
>     end
> 
>     def self.down
>       execute "ALTER TABLE inventory_movements DROP CONSTRAINT fk_inventory_movement_part"
>       execute "ALTER TABLE inventory_movements DROP CONSTRAINT fk_inventory_movement_providor"
>       execute "ALTER TABLE inventory_parts DROP CONSTRAINT fk_inventory_parts_category"
>     end
>   end


*Modified 007_keys_and_modifications.rb*

> class KeysAndModifications < ActiveRecord::Migration
>     def self.up
>       execute <<-SQL
>         ALTER TABLE inventory_parts ADD
>           CONSTRAINT uk_inventory_part_part_number UNIQUE (part_number);
>       SQL
> 
>       execute <<-SQL
>           ALTER TABLE inventory_categories ADD
>            CONSTRAINT uk_inventory_category_name UNIQUE (name);
>         SQL
> 
>       execute <<-SQL
>           ALTER TABLE inventory_providors ADD
>             CONSTRAINT uk_inventory_providor_identification UNIQUE (identification);
>         SQL
> 
>       add_column :inventory_movements, :user_from_id, :integer
>       add_column :inventory_movements, :user_to_id, :integer
>       add_column :inventory_movements, :warehouse_to_id, :integer
>       add_column :inventory_movements, :warehouse_from_id, :integer
>       add_column :inventory_movements, :serial_number, :string
> 
>       execute <<-SQL
>         ALTER TABLE inventory_movements ADD
>           CONSTRAINT fk_inventory_movement_warehouse_to FOREIGN KEY (warehouse_to_id)
>             REFERENCES inventory_warehouses(id)
>             ON DELETE NO ACTION
>             ON UPDATE NO ACTION;
>       SQL
> 
>       execute <<-SQL
>         ALTER TABLE inventory_movements ADD
>           CONSTRAINT fk_inventory_movement_warehouse_from FOREIGN KEY (warehouse_from_id)
>             REFERENCES inventory_warehouses(id)
>             ON DELETE NO ACTION
>             ON UPDATE NO ACTION;
>       SQL
> 
>       execute <<-SQL
>         ALTER TABLE inventory_movements ADD
>           CONSTRAINT fk_inventory_movement_user FOREIGN KEY (user_id)
>             REFERENCES users(id)
>             ON DELETE NO ACTION
>             ON UPDATE NO ACTION;
>       SQL
> 
>       execute <<-SQL
>         ALTER TABLE inventory_movements ADD
>           CONSTRAINT fk_inventory_movement_user_from FOREIGN KEY (user_from_id)
>             REFERENCES users(id)
>             ON DELETE NO ACTION
>             ON UPDATE NO ACTION;
>       SQL
> 
>       execute <<-SQL
>         ALTER TABLE inventory_movements ADD
>           CONSTRAINT fk_inventory_movement_user_to FOREIGN KEY (user_to_id)
>             REFERENCES users(id)
>             ON DELETE NO ACTION
>             ON UPDATE NO ACTION;
>       SQL
> 
>       add_column :inventory_parts, :where, :string
> 
>     end
> 
>     def self.down
>       execute "ALTER TABLE inventory_parts DROP CONSTRAINT uk_inventory_part_part_number"
>       execute "ALTER TABLE inventory_categories DROP CONSTRAINT uk_inventory_category_name"
>       execute "ALTER TABLE inventory_providors DROP CONSTRAINT uk_inventory_providor_identification"
> 
>       execute "ALTER TABLE inventory_movements DROP CONSTRAINT fk_inventory_movement_user"
>       execute "ALTER TABLE inventory_movements DROP CONSTRAINT fk_inventory_movement_user_from"
>       execute "ALTER TABLE inventory_movements DROP CONSTRAINT fk_inventory_movement_user_to"
>       execute "ALTER TABLE inventory_movements DROP CONSTRAINT fk_inventory_movement_warehouse_from"
>       execute "ALTER TABLE inventory_movements DROP CONSTRAINT fk_inventory_movement_warehouse_to"
> 
>       remove_column :inventory_movements, :user_from_id
>       remove_column :inventory_movements, :user_to_id
>       remove_column :inventory_movements, :warehouse_to_id
>       remove_column :inventory_movements, :warehouse_from_id
>       remove_column :inventory_movements, :serial_number
>       remove_column :inventory_parts, :where
>     end
>   end

------------------
Hope this helps,

Best regards,
Albertas
